# Generated by Django 2.1.5 on 2019-01-27 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_auto_20190124_2033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_saved', to='books.Book')),
                ('save_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
