# Generated by Django 2.1.5 on 2019-02-01 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0002_savedbooks_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbooks',
            name='books_saved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='savedbooks',
            name='save_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
