# Generated by Django 2.1.5 on 2019-01-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190117_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='avatar/'),
        ),
    ]
