# Generated by Django 2.1.5 on 2019-01-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='avatar/', verbose_name='profile_pic'),
        ),
    ]
