# Generated by Django 2.1.5 on 2019-01-23 23:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190122_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to=users.models.user_directory_path, verbose_name='profile_pic'),
        ),
    ]
