# Generated by Django 2.1.5 on 2019-01-23 23:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190123_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='None/no-img.jpg', upload_to=users.models.user_directory_path, verbose_name='profile_pic'),
        ),
    ]
