# Generated by Django 2.2b1 on 2019-02-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190126_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Mountain View', max_length=50),
            preserve_default=False,
        ),
    ]
