# Generated by Django 2.2b1 on 2019-02-13 04:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
