# Generated by Django 2.1.5 on 2019-01-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190121_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
