# Generated by Django 2.1.5 on 2019-02-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190131_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character', max_length=13, verbose_name='ISBN'),
        ),
    ]
