# Generated by Django 2.2b1 on 2019-02-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190202_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='city',
            field=models.CharField(default='Mountain View', max_length=50),
            preserve_default=False,
        ),
    ]
