# Generated by Django 2.2b1 on 2019-02-13 04:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
