# Generated by Django 2.2b1 on 2019-02-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('1', 'New(never used)'), ('2', 'Used(like new)'), ('3', 'Used(good)'), ('3', 'Used(acceptable)'), ('4', 'Others')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
