# Generated by Django 2.2b1 on 2019-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character', max_length=14, verbose_name='ISBN'),
        ),
    ]
