# Generated by Django 2.2b1 on 2019-02-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='product',
        ),
    ]
