# Generated by Django 2.1.5 on 2019-02-08 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190207_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='books.Book'),
        ),
    ]
