# Generated by Django 2.1.5 on 2019-02-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190208_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='id',
        ),
    ]
