# Generated by Django 2.1.5 on 2019-02-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190208_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='order',
        ),
    ]
