# Generated by Django 2.1.5 on 2019-02-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190208_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='offer',
        ),
    ]
