# Generated by Django 2.2a1 on 2019-02-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_braintree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Offer'),
        ),
    ]
